version: "3.9"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"   # maps container port 8000 to localhost:8000
    volumes:
      - .:/app        # optional: live code changes
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
